-- 1번
SELECT
	STUDENT_NAME "학생 이름",
	STUDENT_ADDRESS "주소지"
FROM
	TB_STUDENT
ORDER BY
	STUDENT_NAME;

-- 2번
SELECT
	STUDENT_NAME,
	STUDENT_SSN
FROM
	TB_STUDENT
WHERE ABSENCE_YN='Y'
ORDER BY STUDENT_SSN DESC;

-- 3번
SELECT
	STUDENT_NAME "학생이름",
	STUDENT_NO "학번",
	STUDENT_ADDRESS "거주지 주소"
FROM
	TB_STUDENT
WHERE
	STUDENT_NO LIKE '9%'
AND
	STUDENt_ADDRESS LIKE '경기%'
ORDER BY
	STUDENT_NAME;


-- 4번
SELECT
	PROFESSOR_NAME,
	PROFESSOR_SSN
FROM
	TB_PROFESSOR P
JOIN
	TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE
	D.DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN;


-- 5번
SELECT
	STUDENT_NO,
	TO_CHAR(POINT, 'FM9.00') "학점"
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
AND TERM_NO = 200402
ORDER BY POINT DESC;


-- 6번
SELECT
	STUDENT_NO,
	STUDENT_NAME,
	DEPARTMENT_NAME
FROM
	TB_STUDENT S
JOIN
	TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY STUDENT_NAME;


-- 7번
SELECT
	CLASS_NAME, DEPARTMENT_NAME
FROM
	TB_CLASS C
JOIN
	TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO);


-- 8번
SELECT C.CLASS_NAME, P.PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_CLASS_PROFESSOR CP ON (C.CLASS_NO = CP.CLASS_NO)
JOIN TB_PROFESSOR P ON (CP.PROFESSOR_NO = P.PROFESSOR_NO);


SELECT * FROM TB_CLASS;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_CLASS_PROFESSOR;

-- 9번
SELECT C.CLASS_NAME, P.PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_CLASS_PROFESSOR CP ON (C.CLASS_NO = CP.CLASS_NO)
JOIN TB_PROFESSOR P ON (CP.PROFESSOR_NO = P.PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.CATEGORY = '인문사회'
ORDER BY CLASS_NAME;

-- 10번
SELECT * FROM TB_DEPARTMENT;

SELECT S.STUDENT_NO AS "학번", S.STUDENT_NAME AS "학생 이름", ROUND(AVG(G.POINT), 1) AS "전체 평점"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE D.DEPARTMENT_NAME = '음악학과'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME
ORDER BY "학번";

-- 11번

SELECT D.DEPARTMENT_NAME AS "학과이름", S.STUDENT_NAME AS "학생이름", P.PROFESSOR_NAME AS "지도교수이름"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE S.STUDENT_NO = 'A313047';


-- 12번
SELECT S.STUDENT_NAME, G.TERM_NO
FROM TB_GRADE G
JOIN TB_CLASS C ON (G.CLASS_NO = C.CLASS_NO)
JOIN TB_STUDENT S ON (G.STUDENT_NO = S.STUDENT_NO)
WHERE G.TERM_NO LIKE '2007%'
AND C.CLASS_NAME = '인간관계론';


-- 13번
SELECT C.CLASS_NAME, D.DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON C.DEPARTMENT_NO = D.DEPARTMENT_NO
LEFT JOIN TB_CLASS_PROFESSOR CP ON C.CLASS_NO = CP.CLASS_NO
WHERE D.CATEGORY = '예체능' 
AND CP.CLASS_NO IS NULL;     

-- 14번
SELECT S.STUDENT_NAME, NVL(P.PROFESSOR_NAME,'지도교수 미지정')
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '서반아어학과';

-- 15번
SELECT S.STUDENT_NO AS "학번", S.STUDENT_NAME AS "이름", D.DEPARTMENT_NAME AS "학과 이름", AVG(POINT) AS "평점"
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE S.ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME
HAVING AVG(POINT)>=4.0
ORDER BY "학번";




